[package]
name = "cif_chomper_macros_core"
version = "0.1.0"
edition = "2024"

[dependencies]
cif_chomper_core = {path = "../cif_chomper_core"}
syn = {workspace = true}
proc-macro2 = "1.0.95"
quote = "1.0.40"
