[lib]
crate-type = ["cdylib","lib"]

[package]
name = "cif_chomper_core"
version = "0.1.0"
edition = "2024"


[dependencies]
log = {workspace = true}
const-str = "0.6.4"
env = "1.0.1"
nom = "8.0.0"
rstest = "0.25.0"
