[lib]
proc-macro = true

[package]
name = "cif_chomper_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
cif_chomper_core = {path = "../cif_chomper_core"}
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = {version = "2.0.104", features = ["full"]}
