[package]
name = "cif_chomper"
version = "0.1.0"
edition = "2024"

[dependencies]
const-str = "0.6.2"
env = "1.0.1"
log = "0.4.27"
nom = "8.0.0"
rstest = "0.25.0"
cif_chomper_macros = {path = "../cif_chomper_macros"}